### ISSUE TITLE
Dynamic cloud and moon

### ISSUE THREAD

**Issue by Bossyao168** [esnya/UdonSunController#1]
Is it possible to share the dynamic cloud(shader?) and moon in your vrchat world(EsnyaUdonFactory) ? Appreciate it.

**Comment by esnya** [comment]
Use a dynamic skybox shader which refs Directional Light such as https://assetstore.unity.com/packages/tools/particles-effects/aio-dynamic-sky-102517

**Comment by justanotherguy6** [comment]
> Use a dynamic skybox shader which refs Directional Light such as https://assetstore.unity.com/packages/tools/particles-effects/aio-dynamic-sky-102517


JPN
「このシェーダーはもうUNITYストアでは入手できません。このUnityPackageをお持ちでしたら、アップロードして共有していただけますか？」

「次のシェーダーはまだ入手可能でしょうか？ 『EsnyaUnityParticles』と『EAA / Fake Directional Light』。」

ENG
1. "this shader is no longer available on the UNITY store. Do you have this unitypackage you could upload and share?

2. Are the following shaders still available ? "EsnyaUnityParticles" & "EAA Fake Directional Light".
