### ISSUE TITLE
[Feature Request] Move away from continuous to manual sync + Late Join support

### ISSUE THREAD

**Issue by Legoman99573** [esnya/UdonSunController#11]
For the sanity of syncing, this can be useful and prevent network sync issues caused by continuous as it can cause issues as some users would still see the sky daytime while others see it night time. Maybe updating it when they drop it to remote users.

**Comment by esnya** [comment]
This code was written before the Udon Network Update. There are no synchronized variables. Therefore, We can use `BehaviourSyncMode.None`. Will be updated soon.
